### Import Modules and Libraries

In [106]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split,cross_validate,GridSearchCV
from sklearn.metrics import precision_recall_fscore_support as score,confusion_matrix,accuracy_score
from sklearn.preprocessing import StandardScaler

### Importing Dataset

In [156]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Dropping of Columns which is no use for model i.e RowNumber, CustomerID and Surname

In [157]:
dataset.drop(columns=["RowNumber","CustomerId","Surname"],axis=1,inplace=True)
dataset.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Factorising and Extracting Dummy variables

In [158]:
dataset.Gender = pd.factorize(dataset.Gender)[0]
Dummies = pd.get_dummies(dataset["Geography"],drop_first=True)
dataset = pd.concat([Dummies,dataset],axis=1)
dataset.drop(["Geography"],axis=1,inplace=True)
dataset.head()

,Germany,Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,0,619,0,42,2,0.00,1,1,1,101348.88,1
1,0,1,608,0,41,1,83807.86,1,0,1,112542.58,0
2,0,0,502,0,42,8,159660.80,3,1,0,113931.57,1
3,0,0,699,0,39,1,0.00,2,0,0,93826.63,0
4,0,1,850,0,43,2,125510.82,1,1,1,79084.10,0

### Scaling of Features

In [159]:
sc = StandardScaler()
dataset.iloc[:,:-1] = sc.fit_transform(dataset.iloc[:,:-1])
dataset.head()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

,Germany,Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,-0.578736,-0.573809,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886,1
1,-0.578736,1.742740,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534,0
2,-0.578736,-0.573809,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687,1
3,-0.578736,-0.573809,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918,0
4,-0.578736,1.742740,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276,0

### Model Selection and hyperparameter Tuning

In [109]:
rf = RandomForestClassifier()
param = {
    'n_estimators':[10,150,300],
    'max_depth': [30, 60, 90, None]
}
gs = GridSearchCV(rf,param,n_jobs=-1,cv=5)
gs_fit = gs.fit(dataset.iloc[:,:-1],dataset.iloc[:,11])
pd.DataFrame(gs_fit.cv_results_).sort_values("mean_test_score",ascending=False)[0:5]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split3_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split4_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('std_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
2,7.776946,0.140117,0.337007,0.002226,30,300,"{'max_depth': 30, 'n_estimators': 300}",0.861069,0.874063,0.864,...,0.8657,0.004616,1,1.0,1.0,1.000000,1.0,1.0,1.000000,0.00000
8,7.894279,0.564271,0.347202,0.011086,90,300,"{'max_depth': 90, 'n_estimators': 300}",0.859570,0.873563,0.862,...,0.8651,0.005040,2,1.0,1.0,1.000000,1.0,1.0,1.000000,0.00000
11,7.186488,0.507604,0.337003,0.054266,None,300,"{'max_depth': None, 'n_estimators': 300}",0.863068,0.873063,0.861,...,0.8647,0.004338,3,1.0,1.0,1.000000,1.0,1.0,1.000000,0.00000
5,7.796335,0.567509,0.356996,0.021421,60,300,"{'max_depth': 60, 'n_estimators': 300}",0.861069,0.876062,0.863,...,0.8644,0.006406,4,1.0,1.0,1.000000,1.0,1.0,1.000000,0.00000
7,4.335916,0.741757,0.189292,0.007469,90,150,"{'max_depth': 90, 'n_estimators': 150}",0.862569,0.875062,0.862,...,0.8644,0.005740,4,1.0,1.0,0.999875,1.0,1.0,0.999975,0.00005

In [110]:
gb = GradientBoostingClassifier()
param = {
    'n_estimators':[10,150,300],
    'max_depth': [30, 60, 90, None],
    'learning_rate':[0.1]
}
gb = GridSearchCV(rf,param,n_jobs=-1,cv=5)
gb_fit = gs.fit(dataset.iloc[:,:-1],dataset.iloc[:,11])
pd.DataFrame(gs_fit.cv_results_).sort_values("mean_test_score",ascending=False)[0:5]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split3_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split4_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('std_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
5,8.617664,1.000739,0.468931,0.121303,60,300,"{'max_depth': 60, 'n_estimators': 300}",0.864068,0.874563,0.8650,...,0.8663,0.004259,1,1.0,1.0,1.0,1.0,1.0,1.0,0.0
8,10.701472,0.763523,0.430353,0.056835,90,300,"{'max_depth': 90, 'n_estimators': 300}",0.866567,0.873063,0.8625,...,0.8649,0.004754,2,1.0,1.0,1.0,1.0,1.0,1.0,0.0
2,8.586882,0.994600,0.439948,0.096222,30,300,"{'max_depth': 30, 'n_estimators': 300}",0.861569,0.874563,0.8645,...,0.8648,0.005009,3,1.0,1.0,1.0,1.0,1.0,1.0,0.0
11,7.525890,0.485506,0.312820,0.040956,None,300,"{'max_depth': None, 'n_estimators': 300}",0.861069,0.873063,0.8635,...,0.8646,0.004378,4,1.0,1.0,1.0,1.0,1.0,1.0,0.0
10,4.417870,0.302332,0.186494,0.011700,None,150,"{'max_depth': None, 'n_estimators': 150}",0.861069,0.870565,0.8645,...,0.8643,0.003350,5,1.0,1.0,1.0,1.0,1.0,1.0,0.0

### Splitting The Datasets

In [160]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,11].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Train and fitting of models

In [113]:
rf = RandomForestClassifier(n_estimators=300,max_depth=30,n_jobs=-1)
rf_fit = rf.fit(X_train,y_train)
rf_pred = rf_fit.predict(X_test)
precision, recall, fscore, support = score(y_test,rf_pred,average='binary')
print("Precision: {}/ Recall: {}/ Fscore: {}/ Accuracy: {}".format(
    round(precision,3),round(recall,3),round(fscore,3),round(accuracy_score(y_test,rf_pred),3)))

Precision: 0.741/ Recall: 0.536/ Fscore: 0.622/ Accuracy: 0.868

In [114]:
gb = GradientBoostingClassifier(n_estimators=300,max_depth=60,learning_rate=0.1)
gb_fit = gb.fit(X_train,y_train)
gb_pred = gb_fit.predict(X_test)
precision, recall, fscore, support = score(y_test,rf_pred,average='binary')
print("Precision: {}/ Recall: {}/ Fscore: {}/ Accuracy: {}".format(
    round(precision,3),round(recall,3),round(fscore,3),round(accuracy_score(y_test,rf_pred),3)))

Precision: 0.741/ Recall: 0.536/ Fscore: 0.622/ Accuracy: 0.868

### Confusion matrix of Both Models

In [163]:
print("RF CM: \n{}".format(confusion_matrix(y_test,rf_pred)))
print("GB CM: \n{}".format(confusion_matrix(y_test,gb_pred)))

RF CM:
[[1519   76]
 [ 188  217]]
GB CM:
[[1397  198]
 [ 178  227]]

### ANN

In [95]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.

In [117]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 3s 356us/step - loss: 0.4959 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.4143 - acc: 0.8204
Epoch 3/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.4017 - acc: 0.8241
Epoch 4/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.3935 - acc: 0.8280
Epoch 5/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3846 - acc: 0.8317
Epoch 6/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3792 - acc: 0.8309
Epoch 7/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3731 - acc: 0.8391
Epoch 8/100
8000/8000 [==============================] - 2s 199us/step - loss: 0.3689 - acc: 0.8459
Epoch 9/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3663 - acc: 0.8477
Epoch 10/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3633 - acc: 0.8522
Epoch 11/100
8000/8000 [==============================] - 2s 214us/step - loss: 0.3611 - acc: 0.8526
Epoch 12/100
8000/8000 [==============================] - 2s 221us/step - loss: 0.3584 - acc: 0.8550
Epoch 13/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.3568 - acc: 0.8560
Epoch 14/100
8000/8000 [==============================] - 2s 208us/step - loss: 0.3561 - acc: 0.8550
Epoch 15/100
8000/8000 [==============================] - 2s 237us/step - loss: 0.3538 - acc: 0.8545
Epoch 16/100
8000/8000 [==============================] - 1s 184us/step - loss: 0.3533 - acc: 0.8545
Epoch 17/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3524 - acc: 0.8556
Epoch 18/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3514 - acc: 0.8547
Epoch 19/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.3497 - acc: 0.8595
Epoch 20/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3500 - acc: 0.8579
Epoch 21/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3486 - acc: 0.8572
Epoch 22/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3483 - acc: 0.8585
Epoch 23/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.3474 - acc: 0.8591
Epoch 24/100
8000/8000 [==============================] - 2s 217us/step - loss: 0.3464 - acc: 0.8582
Epoch 25/100
8000/8000 [==============================] - 2s 254us/step - loss: 0.3450 - acc: 0.8585
Epoch 26/100
8000/8000 [==============================] - 2s 205us/step - loss: 0.3449 - acc: 0.8562
Epoch 27/100
8000/8000 [==============================] - 2s 226us/step - loss: 0.3444 - acc: 0.8582
Epoch 28/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.3432 - acc: 0.8586
Epoch 29/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3423 - acc: 0.8576
Epoch 30/100
8000/8000 [==============================] - 2s 212us/step - loss: 0.3428 - acc: 0.8585
Epoch 31/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3432 - acc: 0.8577
Epoch 32/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3415 - acc: 0.8592
Epoch 33/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3412 - acc: 0.8591
Epoch 34/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.3414 - acc: 0.8584
Epoch 35/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3414 - acc: 0.8614
Epoch 36/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.3405 - acc: 0.8591
Epoch 37/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3411 - acc: 0.8604
Epoch 38/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3409 - acc: 0.8602
Epoch 39/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.3399 - acc: 0.8602
Epoch 40/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.3401 - acc: 0.8609
Epoch 41/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.3403 - acc: 0.8624
Epoch 42/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.3406 - acc: 0.8591
Epoch 43/100
8000/8000 [==============================] - 2s 238us/step - loss: 0.3396 - acc: 0.8615
Epoch 44/100
8000/8000 [==============================] - 2s 214us/step - loss: 0.3403 - acc: 0.8620
Epoch 45/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.3398 - acc: 0.8595
Epoch 46/100
8000/8000 [==============================] - 2s 287us/step - loss: 0.3391 - acc: 0.8595
Epoch 47/100
8000/8000 [==============================] - 3s 336us/step - loss: 0.3395 - acc: 0.8644
Epoch 48/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.3392 - acc: 0.8582
Epoch 49/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3393 - acc: 0.8624
Epoch 50/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.3390 - acc: 0.8621
Epoch 51/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3387 - acc: 0.8595
Epoch 52/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3391 - acc: 0.8581
Epoch 53/100
8000/8000 [==============================] - 2s 224us/step - loss: 0.3399 - acc: 0.8604
Epoch 54/100
8000/8000 [==============================] - 2s 232us/step - loss: 0.3391 - acc: 0.8602
Epoch 55/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.3389 - acc: 0.8596
Epoch 56/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3381 - acc: 0.8619
Epoch 57/100
8000/8000 [==============================] - 2s 229us/step - loss: 0.3389 - acc: 0.8604
Epoch 58/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.3393 - acc: 0.8612
Epoch 59/100
8000/8000 [==============================] - 1s 181us/step - loss: 0.3379 - acc: 0.8620
Epoch 60/100
8000/8000 [==============================] - 1s 181us/step - loss: 0.3393 - acc: 0.8595
Epoch 61/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3389 - acc: 0.8594
Epoch 62/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3382 - acc: 0.8617
Epoch 63/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.3388 - acc: 0.8625
Epoch 64/100
8000/8000 [==============================] - 2s 227us/step - loss: 0.3384 - acc: 0.8627
Epoch 65/100
8000/8000 [==============================] - 2s 293us/step - loss: 0.3386 - acc: 0.8622 1s - los
Epoch 66/100
8000/8000 [==============================] - 2s 281us/step - loss: 0.3374 - acc: 0.8627
Epoch 67/100
8000/8000 [==============================] - 2s 284us/step - loss: 0.3380 - acc: 0.8629
Epoch 68/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.3386 - acc: 0.8605
Epoch 69/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.3382 - acc: 0.8585
Epoch 70/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3388 - acc: 0.8602
Epoch 71/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3386 - acc: 0.8607
Epoch 72/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3373 - acc: 0.8577
Epoch 73/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3375 - acc: 0.8605
Epoch 74/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3386 - acc: 0.8595
Epoch 75/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3379 - acc: 0.8579
Epoch 76/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3380 - acc: 0.8609
Epoch 77/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.3370 - acc: 0.8601
Epoch 78/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.3377 - acc: 0.8627
Epoch 79/100
8000/8000 [==============================] - 2s 220us/step - loss: 0.3362 - acc: 0.8605
Epoch 80/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3374 - acc: 0.8616
Epoch 81/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3372 - acc: 0.8610
Epoch 82/100

8000/8000 [==============================] - 1s 172us/step - loss: 0.3372 - acc: 0.8606
Epoch 83/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.3385 - acc: 0.8614
Epoch 84/100
8000/8000 [==============================] - 2s 199us/step - loss: 0.3365 - acc: 0.8617
Epoch 85/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.3373 - acc: 0.8616
Epoch 86/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.3365 - acc: 0.8624
Epoch 87/100
8000/8000 [==============================] - 2s 275us/step - loss: 0.3372 - acc: 0.8612
Epoch 88/100
8000/8000 [==============================] - 2s 238us/step - loss: 0.3366 - acc: 0.8599
Epoch 89/100
8000/8000 [==============================] - 2s 241us/step - loss: 0.3360 - acc: 0.8615
Epoch 90/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.3372 - acc: 0.8606
Epoch 91/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3361 - acc: 0.8609
Epoch 92/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.3361 - acc: 0.8630
Epoch 93/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.3356 - acc: 0.8614
Epoch 94/100
8000/8000 [==============================] - 2s 253us/step - loss: 0.3365 - acc: 0.8617
Epoch 95/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.3364 - acc: 0.8619
Epoch 96/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.3370 - acc: 0.8634
Epoch 97/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3363 - acc: 0.8602
Epoch 98/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.3369 - acc: 0.8606
Epoch 99/100
8000/8000 [==============================] - 2s 205us/step - loss: 0.3370 - acc: 0.8605
Epoch 100/100
8000/8000 [==============================] - 2s 239us/step - loss: 0.3365 - acc: 0.8611

### Confusion matrix of ANN

In [168]:
ann_pred = classifier.predict(X_test)
ann_pred = (ann_pred > 0.5)
confusion_matrix(y_test,ann_pred)

array([[1523,   72],
       [ 202,  203]], dtype=int64)

### Stats of All the models

In [171]:
#RF Stats
print("RF || Accuracy: {}, Precision: {}, Recall: {}".format(
    round((1519+217)/(2000),3),round((1519/(1519+217)),3),round((1519/(1519+217)),3)))
#GB Stats
print("GB || Accuracy: {}, Precision: {}, Recall: {}".format(
    round((1397+227)/(2000),3),round((1397/(1397+198)),3),round((1397/(1397+178)),3)))
#ANN Stats
print("ANN || Accuracy: {}, Precision: {}, Recall: {}".format(
    round((1523+203)/(2000),3),round((1523/(1523+72)),3),round((1523/(1523+202)),3)))

RF || Accuracy: 0.868, Precision: 0.875, Recall: 0.875
GB || Accuracy: 0.812, Precision: 0.876, Recall: 0.887
ANN || Accuracy: 0.863, Precision: 0.955, Recall: 0.883

### Prediction from all the models on Values
<font color='green'>
Geography = France<br>
Credit Score = 600<br>
Gender = Male<br>
Age = 40<br>
Tenure = 3<br>
Balance = 60000<br>
Number of products = 2<br>
Has Credit Card = Yes<br>
Is active member = Yes<br>
Estimated Salary = 50000
</font>

In [172]:
rf_predict = rf_fit.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))
gb_predict = gb_fit.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))
ann_predict = classifier.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))
print("Rf: {}/ GB: {}/ ANN: {}".format(rf_predict,gb_predict,ann_predict>0.5))

Rf: [0]/ GB: [0]/ ANN: [[False]]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

#### So Answer is False or Customer will not Leave the bank